development:
  adapter: postgresql
  encoding: unicode
  database: milgram_development
  pool: 5
  username: milgram
  password: milgram

test:
  adapter: postgresql
  encoding: unicode
  database: milgram_test
  pool: 5
  username: milgram
  password: milgram
